#
# MAKEFILE -- build rules for freemodbus/modbus/include.
#
# Copyright (c) 2024 Selectronic Australia Pty Ltd. All rights reserved.
# SPDX-License-Identifier: LicenseRef-Selectronic
#

export PROJECT ?= freemodbus

include makeshift.mk
