#
# MAKEFILE -- build rules for freemodbus/modbus/port/include.
#
# Copyright (c) 2024 Selectronic Australia Pty Ltd. All rights reserved.
# SPDX-License-Identifier: LicenseRef-Selectronic
#

include makeshift.mk
